-- Fases 2 a 6: portal completo, escritas resilientes, Storage, webhook e auditoria.
-- Esta migration remove a dependência operacional de Apps Script, Sheets e Drive.

alter type public.integration_trigger_source add value if not exists 'webhook';

begin;

do $$
begin
  create type public.ticket_source_system as enum ('monday', 'portal');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.external_sync_status as enum ('not_required', 'pending', 'synced', 'failed');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.comment_source as enum ('legacy', 'portal', 'monday', 'system');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.webhook_event_status as enum ('received', 'processing', 'processed', 'ignored', 'failed');
exception when duplicate_object then null;
end $$;

alter table public.tickets alter column monday_item_id drop not null;
alter table public.tickets
  add column if not exists source_system public.ticket_source_system not null default 'monday',
  add column if not exists portal_reference text,
  add column if not exists created_by_user_id uuid references public.profiles(id) on delete set null,
  add column if not exists external_sync_status public.external_sync_status not null default 'synced',
  add column if not exists external_sync_error text,
  add column if not exists last_activity_at timestamptz not null default now(),
  add column if not exists sla_deadline timestamptz,
  add column if not exists sla_warning_minutes integer not null default 120 check (sla_warning_minutes >= 0),
  add column if not exists archived_at timestamptz;

update public.tickets
set source_system = 'monday',
    external_sync_status = case when monday_item_id is null then 'pending'::public.external_sync_status else 'synced'::public.external_sync_status end,
    last_activity_at = greatest(coalesce(source_updated_at, opened_at, created_at), created_at)
where true;

create unique index if not exists tickets_portal_reference_unique_idx
  on public.tickets (portal_reference)
  where portal_reference is not null;
create index if not exists tickets_activity_idx on public.tickets (last_activity_at desc);
create index if not exists tickets_external_sync_idx
  on public.tickets (external_sync_status, created_at)
  where external_sync_status in ('pending', 'failed');

create table if not exists public.sla_policies (
  priority_key public.ticket_priority_key primary key,
  target_business_minutes integer not null check (target_business_minutes > 0),
  warning_minutes integer not null default 120 check (warning_minutes >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.sla_policies (priority_key, target_business_minutes, warning_minutes)
values
  ('critical', 240, 120),
  ('high', 960, 120),
  ('medium', 1920, 120),
  ('low', 6000, 120)
on conflict (priority_key) do update
set target_business_minutes = excluded.target_business_minutes,
    warning_minutes = excluded.warning_minutes,
    active = true,
    updated_at = now();

create table if not exists public.business_hours (
  id bigint generated by default as identity primary key,
  weekday smallint not null check (weekday between 1 and 5),
  segment_order smallint not null check (segment_order > 0),
  start_time time not null,
  end_time time not null,
  active boolean not null default true,
  constraint business_hours_valid_range check (end_time > start_time),
  constraint business_hours_unique unique (weekday, segment_order)
);

insert into public.business_hours (weekday, segment_order, start_time, end_time)
select weekday, segment_order, start_time, end_time
from (values
  (1, 1, '07:42'::time, '13:00'::time), (1, 2, '14:00'::time, '17:00'::time),
  (2, 1, '07:42'::time, '13:00'::time), (2, 2, '14:00'::time, '17:00'::time),
  (3, 1, '07:42'::time, '13:00'::time), (3, 2, '14:00'::time, '17:00'::time),
  (4, 1, '07:42'::time, '13:00'::time), (4, 2, '14:00'::time, '17:00'::time),
  (5, 1, '07:42'::time, '13:00'::time), (5, 2, '14:00'::time, '17:00'::time)
) as schedule(weekday, segment_order, start_time, end_time)
on conflict (weekday, segment_order) do update
set start_time = excluded.start_time, end_time = excluded.end_time, active = true;

create table if not exists public.business_holidays (
  holiday_date date primary key,
  description text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.ticket_comments (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  author_user_id uuid references public.profiles(id) on delete set null,
  author_email_snapshot text not null default '',
  body text not null default '',
  source public.comment_source not null default 'portal',
  monday_sync_status public.external_sync_status not null default 'pending',
  monday_sync_error text,
  monday_synced_at timestamptz,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ticket_comments_email_lowercase check (author_email_snapshot = lower(author_email_snapshot)),
  constraint ticket_comments_content check (length(trim(body)) > 0 or raw_payload ? 'attachment_only')
);

create index if not exists ticket_comments_ticket_idx on public.ticket_comments (ticket_id, created_at);
create index if not exists ticket_comments_pending_idx
  on public.ticket_comments (monday_sync_status, created_at)
  where monday_sync_status in ('pending', 'failed');

alter table public.ticket_attachments alter column monday_asset_id drop not null;

alter table public.ticket_attachments
  add column if not exists comment_id uuid references public.ticket_comments(id) on delete set null,
  add column if not exists storage_bucket text,
  add column if not exists storage_path text,
  add column if not exists uploaded_by uuid references public.profiles(id) on delete set null,
  add column if not exists checksum_sha256 text,
  add column if not exists upload_source public.comment_source not null default 'monday',
  add column if not exists monday_sync_status public.external_sync_status not null default 'synced',
  add column if not exists monday_sync_error text,
  add column if not exists monday_synced_at timestamptz;

create unique index if not exists ticket_attachments_storage_path_unique_idx
  on public.ticket_attachments (storage_bucket, storage_path)
  where storage_path is not null;
create index if not exists ticket_attachments_pending_idx
  on public.ticket_attachments (monday_sync_status, created_at)
  where monday_sync_status in ('pending', 'failed');

create table if not exists public.ticket_status_history (
  id bigint generated by default as identity primary key,
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  previous_status public.ticket_status_bucket,
  new_status public.ticket_status_bucket not null,
  changed_by uuid references public.profiles(id) on delete set null,
  source public.comment_source not null default 'system',
  changed_at timestamptz not null default now()
);
create index if not exists ticket_status_history_ticket_idx
  on public.ticket_status_history (ticket_id, changed_at desc);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  actor_email text not null default '',
  action text not null,
  entity_type text not null,
  entity_id text,
  request_id text,
  success boolean not null default true,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint audit_events_actor_email_lowercase check (actor_email = lower(actor_email))
);
create index if not exists audit_events_created_idx on public.audit_events (created_at desc);
create index if not exists audit_events_entity_idx on public.audit_events (entity_type, entity_id, created_at desc);

create table if not exists public.monday_webhook_events (
  id uuid primary key default gen_random_uuid(),
  dedupe_key text not null unique,
  board_id text not null,
  monday_item_id text not null,
  event_type text not null,
  status public.webhook_event_status not null default 'received',
  attempts integer not null default 0 check (attempts >= 0),
  payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  error_message text
);
create index if not exists monday_webhook_events_status_idx
  on public.monday_webhook_events (status, received_at)
  where status in ('received', 'processing', 'failed');

insert into storage.buckets (id, name, public, file_size_limit)
values ('ticket-attachments', 'ticket-attachments', false, 8388608)
on conflict (id) do update
set public = false, file_size_limit = 8388608;

create or replace function app_private.ticket_is_visible(target_ticket_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.tickets as ticket
    where ticket.id = target_ticket_id
      and (
        app_private.has_support_access()
        or (
          ticket.source_active = true
          and (
            ticket.requester_user_id = (select auth.uid())
            or (
              ticket.requester_email <> ''
              and ticket.requester_email = app_private.current_user_email()
            )
          )
        )
      )
  );
$$;
revoke all on function app_private.ticket_is_visible(uuid) from public, anon;
grant execute on function app_private.ticket_is_visible(uuid) to authenticated;

create or replace function app_private.capture_ticket_status_history()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.ticket_status_history(ticket_id, previous_status, new_status, source)
    values (new.id, null, new.status_bucket, 'system');
  elsif new.status_bucket is distinct from old.status_bucket then
    insert into public.ticket_status_history(ticket_id, previous_status, new_status, source)
    values (new.id, old.status_bucket, new.status_bucket, 'system');
  end if;
  return new;
end;
$$;
revoke all on function app_private.capture_ticket_status_history() from public, anon, authenticated;

drop trigger if exists tickets_capture_status_history on public.tickets;
create trigger tickets_capture_status_history
  after insert or update of status_bucket on public.tickets
  for each row execute function app_private.capture_ticket_status_history();

drop trigger if exists ticket_comments_set_updated_at on public.ticket_comments;
create trigger ticket_comments_set_updated_at
  before update on public.ticket_comments
  for each row execute function app_private.set_updated_at();

drop trigger if exists sla_policies_set_updated_at on public.sla_policies;
create trigger sla_policies_set_updated_at
  before update on public.sla_policies
  for each row execute function app_private.set_updated_at();

alter table public.sla_policies enable row level security;
alter table public.sla_policies force row level security;
alter table public.business_hours enable row level security;
alter table public.business_hours force row level security;
alter table public.business_holidays enable row level security;
alter table public.business_holidays force row level security;
alter table public.ticket_comments enable row level security;
alter table public.ticket_comments force row level security;
alter table public.ticket_status_history enable row level security;
alter table public.ticket_status_history force row level security;
alter table public.audit_events enable row level security;
alter table public.audit_events force row level security;
alter table public.monday_webhook_events enable row level security;
alter table public.monday_webhook_events force row level security;

create policy ticket_comments_select_visible_ticket
  on public.ticket_comments for select to authenticated
  using (app_private.ticket_is_visible(ticket_id));
create policy ticket_status_history_select_visible_ticket
  on public.ticket_status_history for select to authenticated
  using (app_private.ticket_is_visible(ticket_id));
create policy sla_policies_select_authenticated
  on public.sla_policies for select to authenticated using (active = true);
create policy business_hours_select_authenticated
  on public.business_hours for select to authenticated using (active = true);
create policy business_holidays_select_authenticated
  on public.business_holidays for select to authenticated using (active = true);
create policy audit_events_select_admin
  on public.audit_events for select to authenticated using (app_private.is_admin());
create policy monday_webhook_events_select_admin
  on public.monday_webhook_events for select to authenticated using (app_private.is_admin());

-- Replace attachment visibility with explicit ticket ownership/support check.
drop policy if exists ticket_attachments_select_via_ticket on public.ticket_attachments;
create policy ticket_attachments_select_via_ticket
  on public.ticket_attachments for select to authenticated
  using (app_private.ticket_is_visible(ticket_id));

create policy ticket_storage_select_visible_ticket
  on storage.objects for select to authenticated
  using (
    bucket_id = 'ticket-attachments'
    and exists (
      select 1 from public.ticket_attachments as attachment
      where attachment.storage_bucket = bucket_id
        and attachment.storage_path = name
        and app_private.ticket_is_visible(attachment.ticket_id)
    )
  );

revoke all on table public.sla_policies from anon, authenticated;
revoke all on table public.business_hours from anon, authenticated;
revoke all on table public.business_holidays from anon, authenticated;
revoke all on table public.ticket_comments from anon, authenticated;
revoke all on table public.ticket_status_history from anon, authenticated;
revoke all on table public.audit_events from anon, authenticated;
revoke all on table public.monday_webhook_events from anon, authenticated;

grant select on table public.sla_policies to authenticated;
grant select on table public.business_hours to authenticated;
grant select on table public.business_holidays to authenticated;
grant select on table public.ticket_comments to authenticated;
grant select on table public.ticket_status_history to authenticated;
grant select on table public.audit_events to authenticated;
grant select on table public.monday_webhook_events to authenticated;

grant select, insert, update, delete on table public.sla_policies to service_role;
grant select, insert, update, delete on table public.business_hours to service_role;
grant select, insert, update, delete on table public.business_holidays to service_role;
grant select, insert, update, delete on table public.ticket_comments to service_role;
grant select, insert, update, delete on table public.ticket_status_history to service_role;
grant select, insert, update, delete on table public.audit_events to service_role;
grant select, insert, update, delete on table public.monday_webhook_events to service_role;
grant usage, select on sequence public.business_hours_id_seq to service_role;
grant usage, select on sequence public.ticket_status_history_id_seq to service_role;
grant usage, select on sequence public.audit_events_id_seq to service_role;


create table if not exists public.request_rate_limits (
  actor_user_id uuid not null references public.profiles(id) on delete cascade,
  action text not null,
  window_started_at timestamptz not null,
  request_count integer not null default 1 check (request_count > 0),
  updated_at timestamptz not null default now(),
  primary key (actor_user_id, action, window_started_at)
);
create index if not exists request_rate_limits_cleanup_idx
  on public.request_rate_limits (window_started_at);

create or replace function public.consume_rate_limit(
  p_actor_user_id uuid,
  p_action text,
  p_max_count integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_window_start timestamptz;
  v_request_count integer;
begin
  if p_actor_user_id is null
     or length(trim(coalesce(p_action, ''))) = 0
     or p_max_count <= 0
     or p_window_seconds <= 0 then
    raise exception 'Parâmetros de rate limit inválidos.';
  end if;

  v_window_start := to_timestamp(
    floor(extract(epoch from clock_timestamp()) / p_window_seconds) * p_window_seconds
  );

  delete from public.request_rate_limits
  where actor_user_id = p_actor_user_id
    and action = p_action
    and window_started_at < v_window_start - interval '7 days';

  insert into public.request_rate_limits (
    actor_user_id,
    action,
    window_started_at,
    request_count,
    updated_at
  )
  values (p_actor_user_id, p_action, v_window_start, 1, now())
  on conflict (actor_user_id, action, window_started_at)
  do update set
    request_count = public.request_rate_limits.request_count + 1,
    updated_at = now()
  returning request_count into v_request_count;

  return v_request_count <= p_max_count;
end;
$$;

revoke all on function public.consume_rate_limit(uuid, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_rate_limit(uuid, text, integer, integer)
  to service_role;

alter table public.request_rate_limits enable row level security;
alter table public.request_rate_limits force row level security;
revoke all on table public.request_rate_limits from anon, authenticated;
grant select, insert, update, delete on table public.request_rate_limits to service_role;

commit;
