begin;

-- New public objects remain private until grants are explicitly added.
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public;

do $$
begin
  create type public.ticket_status_bucket as enum (
    'open',
    'in_progress',
    'resolved',
    'cancelled'
  );
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create type public.ticket_priority_key as enum (
    'critical',
    'high',
    'medium',
    'low',
    'unknown'
  );
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create type public.integration_run_status as enum (
    'running',
    'succeeded',
    'failed'
  );
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create type public.integration_trigger_source as enum (
    'manual',
    'cron',
    'cli'
  );
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.integration_runs (
  id uuid primary key default gen_random_uuid(),
  integration text not null default 'monday',
  status public.integration_run_status not null default 'running',
  trigger_source public.integration_trigger_source not null,
  triggered_by uuid references public.profiles(id) on delete set null,
  board_id text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  items_received integer not null default 0 check (items_received >= 0),
  items_upserted integer not null default 0 check (items_upserted >= 0),
  attachments_upserted integer not null default 0 check (attachments_upserted >= 0),
  attachments_deactivated integer not null default 0 check (attachments_deactivated >= 0),
  items_deactivated integer not null default 0 check (items_deactivated >= 0),
  error_summary text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint integration_runs_finished_state check (
    (status = 'running' and finished_at is null)
    or (status in ('succeeded', 'failed') and finished_at is not null)
  )
);

create index if not exists integration_runs_started_at_idx
  on public.integration_runs (started_at desc);
create index if not exists integration_runs_status_idx
  on public.integration_runs (status, started_at desc);

create table if not exists public.integration_errors (
  id bigint generated by default as identity primary key,
  integration_run_id uuid not null references public.integration_runs(id) on delete cascade,
  external_id text,
  operation text not null,
  error_code text,
  error_message text not null,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists integration_errors_run_idx
  on public.integration_errors (integration_run_id, created_at);

create table if not exists public.tickets (
  id uuid primary key default gen_random_uuid(),
  board_id text not null,
  monday_item_id text not null,
  title text not null,
  group_external_id text not null,
  group_name text not null,
  status_raw text not null default '',
  status_bucket public.ticket_status_bucket not null default 'open',
  priority_raw text not null default '',
  priority_key public.ticket_priority_key not null default 'unknown',
  requester_name text not null default '',
  requester_email text not null default '',
  requester_user_id uuid references public.profiles(id) on delete set null,
  responsible_name text not null default '',
  request_type text not null default '',
  priority_justification text not null default '',
  root_cause text not null default '',
  current_update text not null default '',
  description text not null default '',
  user_reply_raw text not null default '',
  opened_at timestamptz,
  resolved_at timestamptz,
  source_created_at timestamptz,
  source_updated_at timestamptz,
  source_active boolean not null default true,
  first_synced_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_synced_at timestamptz not null default now(),
  last_sync_run_id uuid references public.integration_runs(id) on delete set null,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tickets_board_item_unique unique (board_id, monday_item_id),
  constraint tickets_requester_email_lowercase check (
    requester_email = lower(requester_email)
  )
);

comment on table public.tickets is
  'Espelho estruturado do estado atual dos chamados do Monday. Google Sheets não participa deste fluxo.';
comment on column public.tickets.user_reply_raw is
  'Campo temporário da Fase 1; será normalizado em ticket_comments na Fase 3.';
comment on column public.tickets.raw_payload is
  'Payload mínimo do item para diagnóstico e reconciliação, sem tokens ou credenciais.';

create index if not exists tickets_requester_email_idx
  on public.tickets (requester_email)
  where requester_email <> '';
create index if not exists tickets_requester_user_idx
  on public.tickets (requester_user_id)
  where requester_user_id is not null;
create index if not exists tickets_status_opened_idx
  on public.tickets (status_bucket, opened_at desc);
create index if not exists tickets_priority_opened_idx
  on public.tickets (priority_key, opened_at desc);
create index if not exists tickets_last_sync_run_idx
  on public.tickets (last_sync_run_id);
create index if not exists tickets_source_active_idx
  on public.tickets (board_id, source_active, last_seen_at desc);

create table if not exists public.ticket_attachments (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  monday_asset_id text not null,
  file_name text not null,
  file_extension text,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  source_url text,
  source_created_at timestamptz,
  source_active boolean not null default true,
  last_seen_at timestamptz not null default now(),
  last_synced_at timestamptz not null default now(),
  last_sync_run_id uuid references public.integration_runs(id) on delete set null,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ticket_attachments_asset_unique unique (ticket_id, monday_asset_id)
);

comment on table public.ticket_attachments is
  'Metadados dos assets do Monday. O arquivo binário será migrado para Supabase Storage na Fase 3.';

create index if not exists ticket_attachments_ticket_idx
  on public.ticket_attachments (ticket_id, source_active);
create index if not exists ticket_attachments_run_idx
  on public.ticket_attachments (last_sync_run_id);

create or replace function app_private.has_support_access()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    (select auth.uid()) is not null
    and exists (
      select 1
      from public.profiles as profile
      where profile.id = (select auth.uid())
        and profile.active = true
        and profile.role in (
          'ti_agent'::public.app_role,
          'admin'::public.app_role
        )
    );
$$;

revoke all on function app_private.has_support_access() from public;
revoke all on function app_private.has_support_access() from anon;
grant execute on function app_private.has_support_access() to authenticated;

create or replace function app_private.current_user_email()
returns text
language sql
stable
security invoker
set search_path = ''
as $$
  select lower(coalesce((select auth.jwt()) ->> 'email', ''));
$$;

revoke all on function app_private.current_user_email() from public;
revoke all on function app_private.current_user_email() from anon;
grant execute on function app_private.current_user_email() to authenticated;

create or replace function app_private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function app_private.set_updated_at() from public;
revoke all on function app_private.set_updated_at() from anon;
revoke all on function app_private.set_updated_at() from authenticated;

create or replace function app_private.link_ticket_requester()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.requester_email = '' then
    new.requester_user_id = null;
    return new;
  end if;

  select profile.id
    into new.requester_user_id
  from public.profiles as profile
  where profile.active = true
    and profile.email = lower(new.requester_email)
  limit 1;

  return new;
end;
$$;

revoke all on function app_private.link_ticket_requester() from public;
revoke all on function app_private.link_ticket_requester() from anon;
revoke all on function app_private.link_ticket_requester() from authenticated;

drop trigger if exists tickets_set_updated_at on public.tickets;
create trigger tickets_set_updated_at
  before update on public.tickets
  for each row execute function app_private.set_updated_at();

drop trigger if exists tickets_link_requester on public.tickets;
create trigger tickets_link_requester
  before insert or update of requester_email on public.tickets
  for each row execute function app_private.link_ticket_requester();

drop trigger if exists ticket_attachments_set_updated_at on public.ticket_attachments;
create trigger ticket_attachments_set_updated_at
  before update on public.ticket_attachments
  for each row execute function app_private.set_updated_at();

-- Link future Auth users to tickets that were already synchronized.
create or replace function app_private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (
    id,
    email,
    full_name,
    role,
    active
  )
  values (
    new.id,
    lower(coalesce(new.email, '')),
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'full_name', '')), ''),
    'requester'::public.app_role,
    true
  )
  on conflict (id) do update
    set email = excluded.email,
        updated_at = now();

  update public.tickets
  set requester_user_id = new.id
  where requester_email = lower(coalesce(new.email, ''))
    and requester_email <> '';

  return new;
end;
$$;

revoke all on function app_private.handle_new_user() from public;
revoke all on function app_private.handle_new_user() from anon;
revoke all on function app_private.handle_new_user() from authenticated;

alter table public.integration_runs enable row level security;
alter table public.integration_runs force row level security;
alter table public.integration_errors enable row level security;
alter table public.integration_errors force row level security;
alter table public.tickets enable row level security;
alter table public.tickets force row level security;
alter table public.ticket_attachments enable row level security;
alter table public.ticket_attachments force row level security;

drop policy if exists tickets_select_owner_or_support on public.tickets;
create policy tickets_select_owner_or_support
  on public.tickets
  for select
  to authenticated
  using (
    app_private.has_support_access()
    or (
      source_active = true
      and (
        requester_user_id = (select auth.uid())
        or (
          requester_email <> ''
          and requester_email = app_private.current_user_email()
        )
      )
    )
  );

drop policy if exists ticket_attachments_select_via_ticket on public.ticket_attachments;
create policy ticket_attachments_select_via_ticket
  on public.ticket_attachments
  for select
  to authenticated
  using (
    app_private.has_support_access()
    or (
      source_active = true
      and exists (
        select 1
        from public.tickets as ticket
        where ticket.id = ticket_attachments.ticket_id
          and ticket.source_active = true
          and (
            ticket.requester_user_id = (select auth.uid())
            or (
              ticket.requester_email <> ''
              and ticket.requester_email = app_private.current_user_email()
            )
          )
      )
    )
  );

drop policy if exists integration_runs_select_admin on public.integration_runs;
create policy integration_runs_select_admin
  on public.integration_runs
  for select
  to authenticated
  using (app_private.is_admin());

drop policy if exists integration_errors_select_admin on public.integration_errors;
create policy integration_errors_select_admin
  on public.integration_errors
  for select
  to authenticated
  using (app_private.is_admin());

revoke all on table public.integration_runs from anon, authenticated;
revoke all on table public.integration_errors from anon, authenticated;
revoke all on table public.tickets from anon, authenticated;
revoke all on table public.ticket_attachments from anon, authenticated;

grant select on table public.integration_runs to authenticated;
grant select on table public.integration_errors to authenticated;
grant select on table public.tickets to authenticated;
grant select on table public.ticket_attachments to authenticated;

grant select, insert, update, delete on table public.integration_runs to service_role;
grant select, insert, update, delete on table public.integration_errors to service_role;
grant select, insert, update, delete on table public.tickets to service_role;
grant select, insert, update, delete on table public.ticket_attachments to service_role;
grant usage, select on sequence public.integration_errors_id_seq to service_role;

commit;
